name: sayable CI
on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc-version: [ "ghc96", "ghc94", "ghc92", "ghc810", "ghc88" ]
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-23.05
      - name: build ${{ matrix.ghc-version }}
        shell: bash
        run: nix build .#sayable.${{ matrix.ghc-version }}
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-23.05
      - name: doc
        shell: bash
        run: nix build .#sayable.TESTS
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-23.05
      - name: doc
        shell: bash
        run: nix build .#sayable.DOC
