name: sayable CI
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc-version: [ "ghc912", "ghc910", "ghc98", "ghc96", "ghc94" ]
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - uses: cachix/cachix-action@v12
        with:
          name: kquick
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: build ${{ matrix.ghc-version }}
        shell: bash
        run: nix build .#sayable.${{ matrix.ghc-version }}
  eng:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-23.11
      - uses: cachix/cachix-action@v12
        with:
          name: kquick
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: build
        shell: bash
        run: nix run github:galoisinc/eng dev build
      - name: test
        shell: bash
        run: nix run github:galoisinc/eng dev test
      - name: nixbuild_all
        shell: bash
        run: nix run github:galoisinc/eng dev nixbuild_all

